version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: discapacidadesMT
    #restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes: 
      - ./discapacidad_Motora/:/app

  db:
    image: mariadb
    container_name: discapacidadesMT-db
    #restart: always
    environment:
      MYSQL_DATABASE: discapacidadesMTdb
      MYSQL_USER: discapacidadesMTdb_user
      MYSQL_PASSWORD: discapacidadesMTdb123
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3310:3306
 
volumes:
  db:    

