# Generated by Django 4.2.1 on 2023-05-11 05:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('genero', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], default=1, max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField()),
                ('grado_estudio', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Primara'), ('2', 'Secundaria'), ('3', 'Prepa'), ('4', 'Licenciatura'), ('5', 'Maestría'), ('6', 'Doctorado'), ('7', 'Posdoctorado')], default=1, max_length=1, verbose_name='Último grado de estudios')),
                ('instituto', models.CharField(max_length=150, verbose_name='Institución a la que pertenece')),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(code='curp_invalido', message='El CURP no tiene un formato válido', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')], verbose_name='C.U.R.P.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
