# Generated by Django 4.2.1 on 2023-05-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActividad', models.CharField(max_length=200, verbose_name='Nombre de la actividad')),
                ('tempo', models.IntegerField(default=0)),
                ('aprendizajes_esperados', models.TextField(verbose_name='Aprendizajes esperados ')),
                ('aspectos_a_favorecer', models.TextField(verbose_name='Aspectos a favorecer')),
                ('Recursos', models.TextField(verbose_name='Recursos')),
                ('competencias_desarrollar', models.TextField(blank=True, null=True, verbose_name='Competencias a desarrollar')),
                ('descripción_actividad', models.TextField(verbose_name='Descripción de la actividad')),
                ('url', models.URLField(max_length=500)),
                ('referencias', models.TextField(verbose_name='Referencias')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidades_motoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDisapacidad', models.CharField(max_length=200, unique=True, verbose_name='Nombre del la discapacidad')),
                ('que_es', models.TextField(verbose_name='¿Que es?')),
                ('que_deve_conocer_familia', models.TextField(verbose_name='¿Que se debe conocer en el entorno familiar?')),
                ('documentacion', models.FileField(upload_to='Documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten Documentos PDF')])),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('referencias', models.TextField(verbose_name='Referencias')),
            ],
        ),
    ]
