# Generated by Django 4.2.1 on 2023-05-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='Documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten Documentos PDF')]),
        ),
    ]
