# Generated by Django 4.2 on 2023-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='Recursos',
            field=models.TextField(default=False, verbose_name='Material:'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='competencias_desarrollar',
            field=models.TextField(null=True, verbose_name='Competencias a desarrollar:'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='desarrollo_atividad',
            field=models.TextField(default=False, verbose_name='Desarrollo de la actividad:'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='objetivo',
            field=models.TextField(default=False, verbose_name='Objetivo:'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tempo',
            field=models.CharField(default=False, max_length=3, verbose_name='Tiempo en miutos:'),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='documentacion',
            field=models.TextField(default=False, verbose_name='Documentacion:'),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='que_deve_conocer_familia',
            field=models.TextField(default=False, verbose_name='¿Que se debe conocer en el entorno familiar?:'),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='que_es',
            field=models.TextField(default=False, verbose_name='¿Que es?:'),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='recomendaciones',
            field=models.TextField(default=False, verbose_name='Recomendaciones:'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombreActividad',
            field=models.CharField(default=False, max_length=200, verbose_name='Nombre de la actividad:'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='url',
            field=models.URLField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='descripcion',
            field=models.TextField(default=False, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='nombreDisapacidad',
            field=models.CharField(default=False, max_length=200, verbose_name='Nombre del la discapacidad'),
        ),
    ]
