# Generated by Django 4.2.1 on 2023-05-05 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_rename_documentacion_discapacidades_motoras_documentaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='que_deve_im',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='que_es_im',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
        migrations.AddField(
            model_name='discapacidades_motoras',
            name='recomendaciones_im',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
