# Generated by Django 4.2.1 on 2023-05-09 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_discapacidades_motoras_que_deve_im_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='que_deve_im',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='que_es_im',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='discapacidades_motoras',
            name='recomendaciones_im',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name=''),
        ),
    ]
