# Generated by Django 4.2 on 2023-04-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_discapacidades_motoras_documentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tempo',
        ),
    ]
