# Generated by Django 4.2.1 on 2023-05-30 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0005_alter_discapacidades_motoras_que_deve_im_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
